package agenthook

import (
	"bytes"
	_ "embed"
	"errors"
	"fmt"
	"os"
	"strings"
)

// scriptRuntime spawns registered commands for a harness that loads a
// JavaScript module; each script profile supplies the glue that calls it.
//
//go:embed script_runtime.js
var scriptRuntime string

const (
	scriptBlockBegin = "// agenthook:begin"
	scriptBlockEnd   = "// agenthook:end"
	scriptConfigDecl = "const config ="
)

// planScriptConfig rewrites a kit-owned module whose registration block holds
// Claude-style nested hooks JSON. The runtime and profile glue are rewritten
// on every write, so a reinstall also upgrades them.
func planScriptConfig(
	spec profileSpec,
	path, marker string,
	argv []string,
	hooks []nativeHook,
	uninstall bool,
) ([]byte, bool, error) {
	existing, err := os.ReadFile(path)
	exists := err == nil
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, false, fmt.Errorf("read agent hook config %s: %w", path, err)
	}
	if !exists && uninstall {
		return nil, false, nil
	}
	if !uninstall && spec.checkScriptLoads != nil {
		if err := spec.checkScriptLoads(path); err != nil {
			return nil, false, err
		}
	}
	root := map[string]any{}
	if exists {
		block, err := scriptBlock(existing, path)
		if err != nil {
			return nil, false, err
		}
		if root, err = decodeJSONConfig(path, block); err != nil {
			return nil, false, err
		}
	}
	if err := applyNestedJSONHooks(root, path, marker, "", "", argv, hooks, uninstall); err != nil {
		return nil, false, err
	}
	encoded, err := marshalJSONConfig(root)
	if err != nil {
		return nil, false, fmt.Errorf("encode agent hook config %s: %w", path, err)
	}
	var data bytes.Buffer
	data.WriteString("// Generated by go.kenn.io/kit/agenthook; Install and Uninstall rewrite this file.\n")
	data.WriteString(scriptBlockBegin + "\n")
	data.WriteString(scriptConfigDecl + " " + strings.TrimSuffix(string(encoded), "\n") + ";\n")
	data.WriteString(scriptBlockEnd + "\n\n")
	data.WriteString(scriptRuntime + "\n")
	data.WriteString(spec.script)
	return data.Bytes(), !bytes.Equal(existing, data.Bytes()), nil
}

// scriptBlock returns the JSON between the registration markers and refuses a
// file agenthook did not write, so a user's module at the path is never lost.
// Markers match whole lines only; JSON escapes newlines, so a hook argument
// that contains a marker can never form one.
func scriptBlock(data []byte, path string) ([]byte, error) {
	lines := strings.Split(string(data), "\n")
	begin, end := -1, -1
	for i, line := range lines {
		line = strings.TrimSuffix(line, "\r")
		if begin < 0 && line == scriptBlockBegin {
			begin = i
		} else if begin >= 0 && line == scriptBlockEnd {
			end = i
			break
		}
	}
	if begin < 0 || end < 0 {
		return nil, fmt.Errorf("agent hook config %s was not written by agenthook", path)
	}
	block := strings.TrimSpace(strings.Join(lines[begin+1:end], "\n"))
	block, foundDecl := strings.CutPrefix(block, scriptConfigDecl)
	block, foundEnd := strings.CutSuffix(block, ";")
	if !foundDecl || !foundEnd {
		return nil, fmt.Errorf("agent hook config %s has a malformed registration block", path)
	}
	return []byte(block), nil
}
