// Package config renders the canonical kenn-io golangci-lint configuration and
// merges an optional repository overlay into it.
//
// golangci-lint has no configuration inheritance, so repositories would
// otherwise copy the shared file and drift. Instead a repository keeps only its
// local additions in an overlay and regenerates .golangci.yml from the two.
package config

import (
	"bytes"
	_ "embed"
	"errors"
	"fmt"
	"slices"

	"gopkg.in/yaml.v3"
)

// Canonical is the shared golangci-lint configuration, byte for byte.
//
//go:embed golangci.yml
var Canonical []byte

// Header is written at the top of every rendered configuration.
const Header = "# Generated by kennlint config from go.kenn.io/kit/lint/config.\n# Put repository-specific additions in the overlay file; do not edit this file by hand.\n"

// Render merges overlay into the canonical configuration and returns the YAML
// to write as .golangci.yml. An empty overlay renders the canonical file.
//
// Merge rules, applied recursively from the document root:
//   - mapping keys present in both: merged; keys only in the overlay: appended
//   - sequences: overlay items are appended unless an equal item already exists
//   - scalars: the overlay value replaces the canonical value
//   - linters.disable and formatters.disable in the overlay remove those names
//     from the rendered enable lists and are not emitted themselves
func Render(overlay []byte) ([]byte, error) {
	base, err := parse(Canonical)
	if err != nil {
		return nil, fmt.Errorf("parsing canonical config: %w", err)
	}
	if len(bytes.TrimSpace(overlay)) > 0 {
		over, err := parse(overlay)
		if err != nil {
			return nil, fmt.Errorf("parsing overlay: %w", err)
		}
		if err := applyDisables(base, over); err != nil {
			return nil, err
		}
		mergeNodes(base, over)
	}

	var out bytes.Buffer
	out.WriteString(Header)
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	if err := enc.Encode(base); err != nil {
		return nil, fmt.Errorf("encoding merged config: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("finishing merged config: %w", err)
	}
	return out.Bytes(), nil
}

func parse(src []byte) (*yaml.Node, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(src, &doc); err != nil {
		return nil, err
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) != 1 || doc.Content[0].Kind != yaml.MappingNode {
		return nil, errors.New("expected a single YAML mapping document")
	}
	return doc.Content[0], nil
}

// applyDisables removes names listed under <section>.disable in the overlay
// from <section>.enable in base, then drops the disable key from the overlay.
func applyDisables(base, over *yaml.Node) error {
	for _, section := range []string{"linters", "formatters"} {
		overSection := mappingValue(over, section)
		if overSection == nil {
			continue
		}
		disable := mappingValue(overSection, "disable")
		if disable == nil {
			continue
		}
		if disable.Kind != yaml.SequenceNode {
			return fmt.Errorf("%s.disable must be a list", section)
		}
		var names []string
		for _, item := range disable.Content {
			names = append(names, item.Value)
		}
		if enable := mappingValue(mappingValue(base, section), "enable"); enable != nil {
			enable.Content = slices.DeleteFunc(enable.Content, func(n *yaml.Node) bool {
				return slices.Contains(names, n.Value)
			})
		}
		deleteKey(overSection, "disable")
	}
	return nil
}

func mergeNodes(base, over *yaml.Node) {
	switch {
	case base.Kind == yaml.MappingNode && over.Kind == yaml.MappingNode:
		for i := 0; i+1 < len(over.Content); i += 2 {
			key, value := over.Content[i], over.Content[i+1]
			if existing := mappingValue(base, key.Value); existing != nil {
				if existing.Kind == value.Kind && (value.Kind == yaml.MappingNode || value.Kind == yaml.SequenceNode) {
					mergeNodes(existing, value)
					continue
				}
				replace(existing, value)
				continue
			}
			base.Content = append(base.Content, key, value)
		}
	case base.Kind == yaml.SequenceNode && over.Kind == yaml.SequenceNode:
		for _, item := range over.Content {
			if !slices.ContainsFunc(base.Content, func(b *yaml.Node) bool { return equalNodes(b, item) }) {
				base.Content = append(base.Content, item)
			}
		}
	default:
		replace(base, over)
	}
}

func replace(dst, src *yaml.Node) {
	comment := dst.HeadComment
	*dst = *src
	if dst.HeadComment == "" {
		dst.HeadComment = comment
	}
}

func equalNodes(a, b *yaml.Node) bool {
	if a.Kind != b.Kind {
		return false
	}
	if a.Kind == yaml.ScalarNode {
		return a.Value == b.Value
	}
	if len(a.Content) != len(b.Content) {
		return false
	}
	for i := range a.Content {
		if !equalNodes(a.Content[i], b.Content[i]) {
			return false
		}
	}
	return true
}

func mappingValue(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}

func deleteKey(m *yaml.Node, key string) {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			m.Content = slices.Delete(m.Content, i, i+2)
			return
		}
	}
}
